# Generated by Django 4.2.5 on 2023-12-07 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeDetails',
            fields=[
                ('db_id', models.AutoField(primary_key=True, serialize=False)),
                ('db_fname', models.CharField(max_length=50)),
                ('db_lname', models.CharField(max_length=50)),
                ('db_email', models.EmailField(max_length=200, unique=True)),
            ],
        ),
    ]
