# Generated by Django 4.1 on 2023-01-10 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('publish_dt', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='UploadImage/')),
            ],
        ),
    ]
