# Generated by Django 4.1 on 2023-01-11 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apps', '0002_commentmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='comment_date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
