# Generated by Django 4.2.5 on 2023-12-07 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('db_id', models.AutoField(primary_key=True, serialize=False)),
                ('db_heading', models.CharField(max_length=25)),
                ('db_content', models.TextField()),
                ('db_date', models.DateField(auto_now=True)),
                ('db_thumbnail', models.ImageField(upload_to='thumbnails')),
            ],
        ),
    ]
