# Generated by Django 4.1 on 2022-11-23 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='joiningDate',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
