# Generated by Django 4.1 on 2022-11-23 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0002_alter_employeedetail_joiningdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedetail',
            name='joiningDate',
            field=models.DateField(null=True),
        ),
    ]
