# Generated by Django 4.1 on 2022-11-23 18:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Application', '0003_alter_employeedetail_joiningdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeEducation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CoursenamePG', models.CharField(max_length=100, null=True)),
                ('CollegePG', models.CharField(max_length=100, null=True)),
                ('ScorePG', models.CharField(max_length=100, null=True)),
                ('PassoutPG', models.DateField(null=True)),
                ('CoursenameG', models.CharField(max_length=100, null=True)),
                ('CollegeG', models.CharField(max_length=100, null=True)),
                ('ScoreG', models.CharField(max_length=100, null=True)),
                ('PassoutG', models.DateField(null=True)),
                ('CoursenameHSC', models.CharField(max_length=100, null=True)),
                ('CollegeHSC', models.CharField(max_length=100, null=True)),
                ('ScoreHSC', models.CharField(max_length=100, null=True)),
                ('PassoutHSC', models.DateField(null=True)),
                ('CoursenameSSC', models.CharField(max_length=100, null=True)),
                ('CollegeSSC', models.CharField(max_length=100, null=True)),
                ('ScoreSSC', models.CharField(max_length=100, null=True)),
                ('PassoutSSC', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
