# Generated by Django 4.1 on 2022-11-23 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0004_employeeeducation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeeeducation',
            name='PassoutG',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='PassoutHSC',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='PassoutPG',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='employeeeducation',
            name='PassoutSSC',
            field=models.CharField(max_length=5, null=True),
        ),
    ]
