# Generated by Django 4.1 on 2022-11-24 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0006_employeeexperience'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeexperience',
            name='company2designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company2duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company2name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company2salary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company3designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company3duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company3name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company3salary',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company4designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company4duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company4name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company4salary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
