# Generated by Django 4.1 on 2022-11-24 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0008_remove_employeeexperience_company4designation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeeexperience',
            name='company4designation',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company4duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company4name',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='employeeexperience',
            name='company4salary',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
