# Generated by Django 4.1 on 2022-11-24 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Application', '0009_employeeexperience_company4designation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeeexperience',
            name='company4designation',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='company4duration',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='company4name',
        ),
        migrations.RemoveField(
            model_name='employeeexperience',
            name='company4salary',
        ),
    ]
