# Generated by Django 4.1 on 2022-12-12 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('author', models.CharField(default='admin', max_length=50)),
                ('timeStamp', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
